// Code generated by "stringer -type=Product -trimprefix Product"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProductUnknown-0]
	_ = x[ProductCockroachDB-1]
	_ = x[ProductMySQL-2]
	_ = x[ProductOracle-3]
	_ = x[ProductPostgreSQL-4]
}

const _Product_name = "UnknownCockroachDBMySQLOraclePostgreSQL"

var _Product_index = [...]uint8{0, 7, 18, 23, 29, 39}

func (i Product) String() string {
	if i < 0 || i >= Product(len(_Product_index)-1) {
		return "Product(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Product_name[_Product_index[i]:_Product_index[i+1]]
}
