// Code generated by "stringer -type=Provider"; DO NOT EDIT.

package objstore

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownStorage-0]
	_ = x[LocalStorage-1]
	_ = x[S3Storage-2]
}

const _Provider_name = "UnknownStorageLocalStorageS3Storage"

var _Provider_index = [...]uint8{0, 14, 26, 35}

func (i Provider) String() string {
	if i < 0 || i >= Provider(len(_Provider_index)-1) {
		return "Provider(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Provider_name[_Provider_index[i]:_Provider_index[i+1]]
}
