// Code generated by "stringer -type=OperationType"; DO NOT EDIT.

package cdc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknownOp-0]
	_ = x[deleteOp-1]
	_ = x[insertOp-2]
	_ = x[updateOp-3]
}

const _OperationType_name = "UnknownOpDeleteOpInsertOpUpdateOp"

var _OperationType_index = [...]uint8{0, 9, 17, 25, 33}

func (i operationType) String() string {
	if i < 0 || i >= operationType(len(_OperationType_index)-1) {
		return "OperationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperationType_name[_OperationType_index[i]:_OperationType_index[i+1]]
}
