// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cdc

import (
	"github.com/cockroachdb/cdc-sink/internal/script"
	"github.com/cockroachdb/cdc-sink/internal/sinktest/all"
	"github.com/cockroachdb/cdc-sink/internal/source/logical"
	"github.com/cockroachdb/cdc-sink/internal/staging/auth/trust"
	"github.com/cockroachdb/cdc-sink/internal/staging/leases"
)

// Injectors from test_fixture.go:

func newTestFixture(fixture *all.Fixture, config *Config) (*testFixture, func(), error) {
	appliers := fixture.Appliers
	authenticator := trust.New()
	baseFixture := fixture.Fixture
	context := baseFixture.Context
	scriptConfig, err := logical.ProvideUserScriptConfig(config)
	if err != nil {
		return nil, nil, err
	}
	loader, err := script.ProvideLoader(scriptConfig)
	if err != nil {
		return nil, nil, err
	}
	baseConfig, err := logical.ProvideBaseConfig(config, loader)
	if err != nil {
		return nil, nil, err
	}
	stagingPool, cleanup, err := logical.ProvideStagingPool(context, baseConfig)
	if err != nil {
		return nil, nil, err
	}
	stagingDB, err := logical.ProvideStagingDB(baseConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	typesLeases, err := leases.ProvideLeases(context, stagingPool, stagingDB)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	metaTable := ProvideMetaTable(config)
	stagers := fixture.Stagers
	watchers := fixture.Watchers
	resolvers, cleanup2, err := ProvideResolvers(context, config, typesLeases, metaTable, stagingPool, stagers, watchers)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	targetPool, cleanup3, err := logical.ProvideTargetPool(context, baseConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	handler := &Handler{
		Appliers:      appliers,
		Authenticator: authenticator,
		Config:        config,
		Resolvers:     resolvers,
		StagingPool:   stagingPool,
		Stores:        stagers,
		TargetPool:    targetPool,
	}
	cdcTestFixture := &testFixture{
		Fixture:   fixture,
		Handler:   handler,
		Resolvers: resolvers,
	}
	return cdcTestFixture, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// test_fixture.go:

type testFixture struct {
	*all.Fixture
	Handler   *Handler
	Resolvers *Resolvers
}
