// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package all

import (
	"github.com/cockroachdb/cdc-sink/internal/sinktest/base"
	"github.com/cockroachdb/cdc-sink/internal/staging/applycfg"
	"github.com/cockroachdb/cdc-sink/internal/staging/memo"
	"github.com/cockroachdb/cdc-sink/internal/staging/stage"
	"github.com/cockroachdb/cdc-sink/internal/target/apply"
	"github.com/cockroachdb/cdc-sink/internal/target/schemawatch"
)

// Injectors from injector.go:

// NewFixture constructs a self-contained test fixture for all services
// in the target sub-packages.
func NewFixture() (*Fixture, func(), error) {
	context, cleanup, err := base.ProvideContext()
	if err != nil {
		return nil, nil, err
	}
	stagingPool, cleanup2, err := base.ProvideStagingPool(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	targetPool, cleanup3, err := base.ProvideTargetPool(context)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	stagingDB, cleanup4, err := base.ProvideStagingDB(context, stagingPool)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	testDB, cleanup5, err := base.ProvideTestDB(context, targetPool)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	fixture := &base.Fixture{
		Context:     context,
		StagingPool: stagingPool,
		TargetPool:  targetPool,
		StagingDB:   stagingDB,
		TestDB:      testDB,
	}
	configs, cleanup6, err := applycfg.ProvideConfigs(context, stagingPool, stagingDB)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	watchers, cleanup7 := schemawatch.ProvideFactory(targetPool)
	appliers, cleanup8 := apply.ProvideFactory(configs, watchers)
	memoMemo, err := memo.ProvideMemo(context, stagingPool, stagingDB)
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	stagers := stage.ProvideFactory(stagingPool, stagingDB)
	watcher, err := ProvideWatcher(context, testDB, watchers)
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	allFixture := &Fixture{
		Fixture:  fixture,
		Appliers: appliers,
		Configs:  configs,
		Memo:     memoMemo,
		Stagers:  stagers,
		Watchers: watchers,
		Watcher:  watcher,
	}
	return allFixture, func() {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
