// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package all

import (
	"github.com/cockroachdb/cdc-sink/internal/sinktest/base"
	"github.com/cockroachdb/cdc-sink/internal/staging/applycfg"
	"github.com/cockroachdb/cdc-sink/internal/staging/memo"
	"github.com/cockroachdb/cdc-sink/internal/staging/stage"
	"github.com/cockroachdb/cdc-sink/internal/staging/version"
	"github.com/cockroachdb/cdc-sink/internal/target/apply"
	"github.com/cockroachdb/cdc-sink/internal/target/schemawatch"
)

// Injectors from injector.go:

// NewFixture constructs a self-contained test fixture for all services
// in the target sub-packages.
func NewFixture() (*Fixture, func(), error) {
	context, cleanup, err := base.ProvideContext()
	if err != nil {
		return nil, nil, err
	}
	sourcePool, cleanup2, err := base.ProvideSourcePool(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	sourceSchema, cleanup3, err := base.ProvideSourceSchema(context, sourcePool)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	stagingPool, cleanup4, err := base.ProvideStagingPool(context)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	stagingSchema, cleanup5, err := base.ProvideStagingSchema(context, stagingPool)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	targetPool, cleanup6, err := base.ProvideTargetPool(context, sourcePool)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	targetSchema, cleanup7, err := base.ProvideTargetSchema(context, targetPool)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	fixture := &base.Fixture{
		Context:      context,
		SourcePool:   sourcePool,
		SourceSchema: sourceSchema,
		StagingPool:  stagingPool,
		StagingDB:    stagingSchema,
		TargetPool:   targetPool,
		TargetSchema: targetSchema,
	}
	configs, cleanup8, err := applycfg.ProvideConfigs(context, stagingPool, stagingSchema)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	watchers, cleanup9 := schemawatch.ProvideFactory(targetPool)
	appliers, cleanup10 := apply.ProvideFactory(configs, targetPool, watchers)
	memoMemo, err := memo.ProvideMemo(context, stagingPool, stagingSchema)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	stagers := stage.ProvideFactory(stagingPool, stagingSchema)
	checker := version.ProvideChecker(stagingPool, memoMemo)
	watcher, err := ProvideWatcher(context, targetSchema, watchers)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	allFixture := &Fixture{
		Fixture:        fixture,
		Appliers:       appliers,
		Configs:        configs,
		Memo:           memoMemo,
		Stagers:        stagers,
		VersionChecker: checker,
		Watchers:       watchers,
		Watcher:        watcher,
	}
	return allFixture, func() {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
