// Code generated by "stringer -type=operationType"; DO NOT EDIT.

package debezium

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknownOp-0]
	_ = x[changeSchemaOp-1]
	_ = x[deleteOp-2]
	_ = x[insertOp-3]
	_ = x[snapshotOp-4]
	_ = x[tombstoneOp-5]
	_ = x[updateOp-6]
	_ = x[beginOp-7]
	_ = x[endOp-8]
}

const _operationType_name = "unknownOpchangeSchemaOpdeleteOpinsertOpsnapshotOptombstoneOpupdateOpbeginOpendOp"

var _operationType_index = [...]uint8{0, 9, 23, 31, 39, 49, 60, 68, 75, 80}

func (i operationType) String() string {
	if i < 0 || i >= operationType(len(_operationType_index)-1) {
		return "operationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _operationType_name[_operationType_index[i]:_operationType_index[i+1]]
}
