// Code generated by "stringer -type=mutationType"; DO NOT EDIT.

package mylogical

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknownMutation-0]
	_ = x[insertMutation-1]
	_ = x[updateMutation-2]
	_ = x[deleteMutation-3]
}

const _mutationType_name = "unknownMutationinsertMutationupdateMutationdeleteMutation"

var _mutationType_index = [...]uint8{0, 15, 29, 43, 57}

func (i mutationType) String() string {
	if i < 0 || i >= mutationType(len(_mutationType_index)-1) {
		return "mutationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _mutationType_name[_mutationType_index[i]:_mutationType_index[i+1]]
}
