// Code generated by "stringer -type=mutationType"; DO NOT EDIT.

package mylogical

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknown-0]
	_ = x[insert-1]
	_ = x[update-2]
	_ = x[delete-3]
}

const _mutationType_name = "unknowninsertupdatedelete"

var _mutationType_index = [...]uint8{0, 7, 13, 19, 25}

func (i mutationType) String() string {
	if i < 0 || i >= mutationType(len(_mutationType_index)-1) {
		return "mutationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _mutationType_name[_mutationType_index[i]:_mutationType_index[i+1]]
}
