// Code generated by "stringer -type=MutationType"; DO NOT EDIT.

package mylogical

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[insert-0]
	_ = x[update-1]
	_ = x[delete-2]
	_ = x[unknown-3]
}

const _MutationType_name = "insertupdatedeleteunknown"

var _MutationType_index = [...]uint8{0, 6, 12, 18, 25}

func (i MutationType) String() string {
	if i < 0 || i >= MutationType(len(_MutationType_index)-1) {
		return "MutationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MutationType_name[_MutationType_index[i]:_MutationType_index[i+1]]
}
