// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package logical

import (
	"context"
	"github.com/cockroachdb/cdc-sink/internal/target/apply"
	"github.com/cockroachdb/cdc-sink/internal/target/apply/fan"
	"github.com/cockroachdb/cdc-sink/internal/target/schemawatch"
)

// Injectors from injector.go:

func Start(ctx context.Context, config *Config, dialect Dialect) (*Loop, func(), error) {
	pool, cleanup, err := ProvidePool(ctx, config)
	if err != nil {
		return nil, nil, err
	}
	watchers, cleanup2 := schemawatch.ProvideFactory(pool)
	appliers, cleanup3 := apply.ProvideFactory(watchers)
	serialPool := ProvideSerializer(config, pool)
	querier := ProvideQuerier(pool, serialPool)
	fans := &fan.Fans{
		Appliers: appliers,
		Pool:     querier,
	}
	stagingDB, err := ProvideStagingDB(config)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	logicalLoop, cleanup4, err := ProvideLoop(ctx, config, dialect, fans, pool, serialPool, stagingDB)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return logicalLoop, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
