// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package seqtest

import (
	"github.com/cockroachdb/replicator/internal/script"
	"github.com/cockroachdb/replicator/internal/sequencer"
	"github.com/cockroachdb/replicator/internal/sequencer/besteffort"
	"github.com/cockroachdb/replicator/internal/sequencer/buffer"
	"github.com/cockroachdb/replicator/internal/sequencer/chaos"
	"github.com/cockroachdb/replicator/internal/sequencer/core"
	"github.com/cockroachdb/replicator/internal/sequencer/decorators"
	"github.com/cockroachdb/replicator/internal/sequencer/immediate"
	"github.com/cockroachdb/replicator/internal/sequencer/retire"
	"github.com/cockroachdb/replicator/internal/sequencer/scheduler"
	script2 "github.com/cockroachdb/replicator/internal/sequencer/script"
	"github.com/cockroachdb/replicator/internal/sequencer/staging"
	"github.com/cockroachdb/replicator/internal/sequencer/switcher"
	"github.com/cockroachdb/replicator/internal/sinktest/all"
)

// Injectors from injector.go:

func NewSequencerFixture(fixture *all.Fixture, config *sequencer.Config, scriptConfig *script.Config) (*Fixture, error) {
	baseFixture := fixture.Fixture
	context := baseFixture.Context
	schedulerScheduler, err := scheduler.ProvideScheduler(context, config)
	if err != nil {
		return nil, err
	}
	stagers := fixture.Stagers
	stagingPool := baseFixture.StagingPool
	watchers := fixture.Watchers
	bestEffort := besteffort.ProvideBestEffort(config, schedulerScheduler, stagers, stagingPool, watchers)
	shim := buffer.ProvideBuffer(config)
	chaosChaos := &chaos.Chaos{
		Config: config,
	}
	stagingSchema := baseFixture.StagingDB
	leases, err := provideLeases(context, stagingPool, stagingSchema)
	if err != nil {
		return nil, err
	}
	targetPool := baseFixture.TargetPool
	coreCore := core.ProvideCore(config, leases, schedulerScheduler, targetPool)
	marker := decorators.ProvideMarker(stagingPool, stagers)
	once := decorators.ProvideOnce(stagingPool, stagers)
	retryTarget := decorators.ProvideRetryTarget(targetPool)
	immediateImmediate := immediate.ProvideImmediate(config, targetPool, marker, once, retryTarget, stagers)
	retireRetire := retire.ProvideRetire(config, stagingPool, stagers)
	configs := fixture.Configs
	diagnostics := fixture.Diagnostics
	loader, err := script.ProvideLoader(context, configs, scriptConfig, diagnostics)
	if err != nil {
		return nil, err
	}
	scriptSequencer := script2.ProvideSequencer(loader, targetPool, watchers)
	stagingStaging := staging.ProvideStaging(config, marker, stagers, stagingPool)
	switcherSwitcher := switcher.ProvideSequencer(bestEffort, coreCore, diagnostics, immediateImmediate, stagingStaging, stagingPool, targetPool)
	seqtestFixture := &Fixture{
		Fixture:    fixture,
		BestEffort: bestEffort,
		Buffer:     shim,
		Chaos:      chaosChaos,
		Core:       coreCore,
		Immediate:  immediateImmediate,
		Retire:     retireRetire,
		Script:     scriptSequencer,
		Staging:    stagingStaging,
		Switcher:   switcherSwitcher,
	}
	return seqtestFixture, nil
}
