{
 "title": "Replicator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "At a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lag Time",
   "type": "stat",
   "description": "This value compares the source cluster wall time of the incoming resolved timestamp (checkpoint) versus the current wall time. This represents the lag of the data which is actionable by Replciator.\n\nNote that if multiple instances of Replicator are present, they may have slightly different views of this lag, based on sampling rate. In all cases, they should agree within one second.",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (kind, target) (source_lag_seconds)",
     "legendFormat": "Source Lag {{kind}} {{target}}"
    },
    {
     "expr": "max by (kind, target) (target_lag_seconds)",
     "legendFormat": "Target Lag {{kind}} {{target}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (schema) (rate(best_effort_accept_applied_count[$__rate_interval]) + rate(best_effort_accept_deferred_count[$__rate_interval]))",
     "legendFormat": "BestEffort {{schema}}"
    },
    {
     "expr": "sum by (schema) (rate(stage_mutations_total[$__rate_interval]))",
     "legendFormat": "Stage {{schema}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(stage_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Stage P99"
    },
    {
     "expr": "sum by (schema) (rate(apply_upserts_total[$__rate_interval]) + rate(apply_deletes_total[$__rate_interval]))",
     "legendFormat": "Apply {{schema}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apply_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Apply P99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(core_sweep_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Sweep P99"
    },
    {
     "expr": "sum by (pool) (pool_acquired_connection_count + pool_idle_connection_count)",
     "legendFormat": "Conns {{pool}}"
    },
    {
     "expr": "sum (rate(http_payload_in_bytes_total_sum[$__rate_interval]))",
     "legendFormat": "HTTP Payloads"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_latency_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "HTTP P99"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "description": "A list of monitored instances of Replicator. The instance name is taken from the Prometheus scraper and can be used to refine the dashboard views.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "targets": [
    { "expr": "cdc_sink_info", "legendFormat": "__auto" },
    { "expr": "cdc_sink_start_seconds * 1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Latency",
     "type": "heatmap",
     "description": "This heatmap shows the number of HTTP requests made to Replicator and how long they took.\n\nSlowness in the HTTP endpoints will reflect performance of the staging database in consistent modes and performance of the target database in immedate or best-effort modes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (le) (rate(http_latency_seconds_bucket[$__rate_interval]))",
       "legendFormat": "{{schema}}"
      }
     ]
    },
    {
     "title": "HTTP Latency P50, P75, P95, P99 vs Payload Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_latency_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P50 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_latency_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P75 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_latency_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P95 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_latency_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P99 {{schema}}"
      },
      {
       "expr": "rate(http_payload_in_bytes_total_sum[$__rate_interval])",
       "legendFormat": "HTTP Rate {{schema}}"
      }
     ]
    },
    {
     "title": "HTTP Payload Size",
     "type": "heatmap",
     "description": "This heatmap shows the distribution of incoming payload sizes. This value will be controlled by the various changefeed flush options.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum by (le) (rate(http_payload_in_bytes_total_bucket[$__rate_interval]))",
       "legendFormat": "{{schema}}"
      }
     ]
    },
    {
     "title": "HTTP Status Codes",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (code) (rate(http_status_codes_total[$__rate_interval]))",
       "legendFormat": "HTTP {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Staging Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stage Latency",
     "type": "heatmap",
     "description": "This heatmap shows the number of staging database interactions and how long they took. Slowness in the staging phase should tend to focus performance investigations on the staging database.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum by (le) (rate(stage_duration_seconds_bucket[$__rate_interval]))",
       "legendFormat": "{{schema}}"
      }
     ]
    },
    {
     "title": "Stage Latency P50, P75, P95, P99 vs Mutation Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(stage_duration_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P50 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(stage_duration_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P75 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(stage_duration_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P95 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(stage_duration_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P99 {{schema}}"
      },
      {
       "expr": "sum(rate(stage_mutations_total[$__rate_interval])) by (schema)",
       "legendFormat": "Stage Rate {{schema}}"
      }
     ]
    },
    {
     "title": "Stage Activity",
     "type": "stat",
     "description": "These gauges shown the rates at which mutations are written and help the operator understand the overall shape of the workload.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "rowsps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (schema, table) (rate(stage_mutations_total[$__rate_interval]))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Stage Write P99",
     "type": "stat",
     "description": "These gauges shown the rates at which mutations are written and help the operator understand the overall shape of the workload.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, schema, table) (rate(stage_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Stage Redelivery Rates",
     "type": "stat",
     "description": "CockroachDB changefeeds guarantee at-least-once delivery of any given mutation. It is normal to see occasional spurts of re-delivery during range splits or cluster maintenance.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "rowsps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(stage_duplicate_mutations_total[$__rate_interval])) by (schema,table)",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Stage Error Rates",
     "type": "stat",
     "description": "Errors writing to the staging tables will cause push-back on the source changefeed and ultimately contribute to the source lag metric.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(stage_errors_total[$__rate_interval])) by (schema,table)",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sequencer Pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sweepers",
     "type": "table",
     "description": "This table shows which instance of Replicator is sweeping any given table.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      { "expr": "core_sweep_active_bool==1", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Sweep Latency P50, P75, P95, P99",
     "type": "timeseries",
     "description": "The core sequencer runs a loop that looks for mutations to apply and then applies them. The time that this loop takes is a function of the number of unapplied mutations and the performance of the staging and target databases. The specific values in this graph should taken as relative to established performance; the absolute values will vary based on the size and shape of the workload being replicated.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(core_sweep_duration_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P50 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(core_sweep_duration_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P75 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(core_sweep_duration_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P95 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(core_sweep_duration_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P99 {{schema}}"
      }
     ]
    },
    {
     "title": "Merge Lag Time",
     "type": "timeseries",
     "description": "Merge lag will correlate with the table that is furthest behind.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "max by (schema) (stage_merge_lag_seconds)",
       "legendFormat": "{{schema}}"
      }
     ]
    },
    {
     "title": "Userscript execution time vs Execution rate",
     "type": "timeseries",
     "description": "This graph may show cases in which excessive time is spent within the JS runtime. This would tend to point towards inefficient user code.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(script_exec_time_seconds_bucket[$__rate_interval])) by (le))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(script_exec_time_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P75"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(script_exec_time_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(script_exec_time_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P99"
      },
      {
       "expr": "sum(rate(script_exec_time_seconds_count[$__rate_interval]))",
       "legendFormat": "Exec Rate"
      }
     ]
    },
    {
     "title": "Stage read P99",
     "type": "stat",
     "description": "This may help to identify cases in which the staging tables are slow to read from. ",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, schema, table) (rate(stage_read_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Stage Read Throughput",
     "type": "stat",
     "description": "The rate at which rows are being read from staging. In a steady-state condition, this should be equal to the rate at which rows are being staged.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "rowsps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (schema, table) (rate(stage_read_rows[$__rate_interval]))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Stage Read Offsets",
     "type": "stat",
     "description": "The age of the data being consumed from staging tables. In consistent modes, the tables for any single changefeed will advance in lock-step. In BestEffort mode, tables will advance independently from one another.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (schema, table) (stage_read_lag_seconds)",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Apply Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apply Latency",
     "type": "heatmap",
     "description": "This heatmap shows the number of target database interactions and how long they took. Slowness in the apply phase should tend to focus performance investigations on the target database.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum by (le) (rate(apply_duration_seconds_bucket[$__rate_interval]))",
       "legendFormat": "{{schema}}"
      }
     ]
    },
    {
     "title": "Apply Latency P50, P75, P95, P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(apply_duration_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P50 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(apply_duration_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P75 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(apply_duration_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P95 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(apply_duration_seconds_bucket[$__rate_interval])) by (le, schema))",
       "legendFormat": "P99 {{schema}}"
      },
      {
       "expr": "sum(rate(apply_upserts_total[$__rate_interval]) + rate(apply_deletes_total[$__rate_interval])) by (schema)",
       "legendFormat": "Apply Rate {{schema}}"
      }
     ]
    },
    {
     "title": "Apply Activity",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "rowsps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(apply_upserts_total[$__rate_interval]) + rate(apply_deletes_total[$__rate_interval])) by (schema, table)",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Table apply P99",
     "type": "stat",
     "description": "This may help to identify tables which are slow to upsert into, possibly indicating insufficient target performance.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, schema, table) (rate(apply_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Table mutation age P99",
     "type": "stat",
     "description": "The age of the mutations being applied to the table. This provides an estimate of the staleness of the data available within the given target table.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, schema, table) (rate(apply_mutation_age_seconds_bucket[$__rate_interval])))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Apply Error Rates",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(apply_errors_total[$__rate_interval])) by (schema,table)",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Best Effort Mode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Best Effort Direct Writes",
     "type": "stat",
     "description": "The number of mutations that were written directly to the target table in best-effort mode.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "Mut/s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(best_effort_accept_applied_count[$__rate_interval])) by (schema,table)",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Best Effort Deferred Writes",
     "type": "stat",
     "description": "The number of mutations that were written to staging, instead of directly to the target table.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Mut/s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(best_effort_accept_deferred_count[$__rate_interval])) by (schema,table)",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection counts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum by (pool) (pool_acquired_connection_count)",
       "legendFormat": "{{pool}} in use"
      },
      {
       "expr": "sum by (pool) (pool_idle_connection_count)",
       "legendFormat": "{{pool}} idle"
      }
     ]
    },
    {
     "title": "Connection acquisition blocking time",
     "type": "timeseries",
     "description": "This shows the amount of time that a process spent waiting to acquire a connection from the respective connection pool. Sustained blocking would indicate an insufficient pool size.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pool) (rate(pool_acquire_wait_seconds[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Staging Pool Dial Latency P95, P99 vs New Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(pool_dial_latency_seconds_bucket{pool=\"staging\"}[$__rate_interval])) by (le, pool))",
       "legendFormat": "P95 {{pool}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pool_dial_latency_seconds_bucket{pool=\"staging\"}[$__rate_interval])) by (le, pool))",
       "legendFormat": "P99 {{pool}}"
      },
      {
       "expr": "sum(rate(pool_dial_latency_seconds_count{pool=\"staging\"}[$__rate_interval])) by (pool)",
       "legendFormat": "New Connection Rate {{pool}}"
      }
     ]
    },
    {
     "title": "Target Pool Dial Latency P95, P99 vs New Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(pool_dial_latency_seconds_bucket{pool=\"target\"}[$__rate_interval])) by (le, pool))",
       "legendFormat": "P95 {{pool}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pool_dial_latency_seconds_bucket{pool=\"target\"}[$__rate_interval])) by (le, pool))",
       "legendFormat": "P99 {{pool}}"
      },
      {
       "expr": "sum(rate(pool_dial_latency_seconds_count{pool=\"target\"}[$__rate_interval])) by (pool)",
       "legendFormat": "New Connection Rate {{pool}}"
      }
     ]
    },
    {
     "title": "Statement cache hit rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (stmtcache_hits_total / (stmtcache_hits_total + stmtcache_misses_total))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Wait Latency P50, P75, P95, P99 vs Task Rate",
     "type": "timeseries",
     "description": "Tasks that write to the target database may execute concurrently only if they would not modify the same row. Tasks that have overlapping row sets must be executed serially in order to guarantee data consistency.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(lockset_exec_wait_seconds_bucket{set=\"scheduler\"}[$__rate_interval])) by (le))",
       "legendFormat": "P50 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(lockset_exec_wait_seconds_bucket{set=\"scheduler\"}[$__rate_interval])) by (le))",
       "legendFormat": "P75 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(lockset_exec_wait_seconds_bucket{set=\"scheduler\"}[$__rate_interval])) by (le))",
       "legendFormat": "P95 {{schema}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(lockset_exec_wait_seconds_bucket{set=\"scheduler\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99 {{schema}}"
      },
      {
       "expr": "rate(lockset_exec_wait_seconds_count{set=\"scheduler\"}[$__rate_interval])",
       "legendFormat": "Task Rate"
      }
     ]
    },
    {
     "title": "Task Events",
     "type": "timeseries",
     "description": "Tasks that have no dependencies on other tasks will be executed immediately, otherwise they are deferred until eligible to run. A task that is executed may be retried if it discovers an ordering requirement that could not be detected during scheduling (e.g. Foreign Key constraints).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum(rate(lockset_immediate_start_count{set=\"scheduler\"}[$__rate_interval]))",
       "legendFormat": "Immediate"
      },
      {
       "expr": "sum(rate(lockset_deferred_start_count{set=\"scheduler\"}[$__rate_interval]))",
       "legendFormat": "Deferred"
      },
      {
       "expr": "sum(rate(lockset_retried_tasks_count{set=\"scheduler\"}[$__rate_interval]))",
       "legendFormat": "Retried"
      }
     ]
    }
   ]
  }
 ]
}