{
 "title": "cdc-sink",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sink Lag Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "logical_commit_latency_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backfill Mode (1 = TRUE)",
   "type": "timeseries",
   "description": "1 = Backfill Mode",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "logical_backfill_status", "legendFormat": "{{loop}}" }
   ]
  },
  {
   "title": "Apply Rate per Table",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "irate(apply_upserts_total[$__rate_interval])",
     "legendFormat": "Upserts_{{table}}"
    },
    {
     "expr": "irate(apply_deletes_total[$__rate_interval])",
     "legendFormat": "Deletes_{{table}}"
    }
   ]
  },
  {
   "title": "Apply Errors per Table",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "irate(apply_errors_total[$__rate_interval])",
     "legendFormat": "Upserts_{{table}}"
    }
   ]
  },
  {
   "title": "CDC Actions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "rate(retry_actions_total[1m])", "legendFormat": "actions" },
    { "expr": "rate(retry_retried_total[1m])", "legendFormat": "retries" },
    { "expr": "rate(retry_aborted_total[1m])", "legendFormat": "retry_aborted_total" }
   ]
  },
  {
   "title": "Commit Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "irate(logical_commit_success_total[$__rate_interval])",
     "legendFormat": "success::{{loop}}"
    },
    {
     "expr": "irate(logical_commit_failure_total[$__rate_interval])",
     "legendFormat": "failure::{{loop}}"
    }
   ]
  },
  {
   "title": "Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(logical_commit_latency_seconds[$__rate_interval]) ",
     "legendFormat": "{{loop}}"
    }
   ]
  },
  {
   "title": "CDC http payload size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by(le) (irate(http_payload_in_bytes_total_bucket{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CDC http payload rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(http_payload_in_bytes_total_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CDC http latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by (le) (irate(http_latency_seconds_bucket{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mutation application latency",
   "type": "heatmap",
   "description": "How long it's taking to apply individual mutations to the target.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum by(le) (irate(apply_duration_seconds_bucket{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Mutation staging latency",
   "type": "heatmap",
   "description": "How long it takes for incoming mutations to be stored within the staging tables.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum by(le) (irate(stage_store_duration_seconds_bucket{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CDC pool dial latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum by(le) (irate(pool_dial_latency_seconds_bucket{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CDC SQL pool ready latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "sum by(le) (irate(pool_sql_ready_latency_seconds_bucket{}[$__rate_interval]))"
    }
   ]
  }
 ]
}