// Code generated by "stringer -type=operation"; DO NOT EDIT.

package db2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknownOp-0]
	_ = x[deleteOp-1]
	_ = x[insertOp-2]
	_ = x[updateOp-3]
	_ = x[beginOp-4]
	_ = x[endOp-5]
	_ = x[rollbackOp-6]
}

const _operation_name = "unknownOpdeleteOpinsertOpupdateOpbeginOpendOprollbackOp"

var _operation_index = [...]uint8{0, 9, 17, 25, 33, 40, 45, 55}

func (i operation) String() string {
	if i < 0 || i >= operation(len(_operation_index)-1) {
		return "operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _operation_name[_operation_index[i]:_operation_index[i+1]]
}
