// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package oraclelogminer

import (
	"github.com/cockroachdb/field-eng-powertools/stopper"
	"github.com/cockroachdb/replicator/internal/util/diag"
)

// Injectors from injector.go:

// Start creates an oracle logminer replication loop using the
// provided configuration.
func Start(context *stopper.Context, config *Config) (*OracleLogminer, error) {
	diagnostics := diag.New(context)
	db, err := ProvideDB(context, config)
	if err != nil {
		return nil, err
	}
	oracleLogminer := &OracleLogminer{
		Diagnostics: diagnostics,
		DB:          db,
	}
	return oracleLogminer, nil
}
