{
 "title": "cdc-sink",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "current_epoch",
    "query": "select extract(epoch from now());"
   }
  ]
 },
 "panels": [
  {
   "title": "CURRENT Lag Time /w CDC sink",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "logical_commit_latency_seconds" }
   ]
  },
  {
   "title": "sink_lag_seconds over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "logical_commit_latency_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Backfill Mode (1 = TRUE)",
   "type": "timeseries",
   "description": "1 = Backfill Mode",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "logical_backfill_status", "legendFormat": "{{loop}}" }
   ]
  },
  {
   "title": "Apply Rate per Table",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "irate(apply_upserts_total[$__rate_interval])",
     "legendFormat": "Upserts_{{table}}"
    },
    {
     "expr": "irate(apply_deletes_total[$__rate_interval])",
     "legendFormat": "Deletes_{{table}}"
    }
   ]
  },
  {
   "title": "Apply Errors per Table",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "irate(apply_errors_total[$__rate_interval])",
     "legendFormat": "Upserts_{{table}}"
    }
   ]
  },
  {
   "title": "Stuck Apply Monitor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "1+ ((rate(logical_commit_success_total[15m]) - rate(logical_commit_failure_total[15m])) < 0) or 0 * ((rate(logical_commit_success_total[15m]) - rate(logical_commit_failure_total[15m])) > 0)",
     "legendFormat": "failure::{{loop}}"
    }
   ]
  },
  {
   "title": "CDC Actions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "rate(retry_actions_total[1m])", "legendFormat": "actions" },
    { "expr": "rate(retry_retried_total[1m])", "legendFormat": "retries" },
    { "expr": "rate(retry_aborted_total[1m])", "legendFormat": "retry_aborted_total" }
   ]
  },
  {
   "title": "Commit Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "irate(logical_commit_success_total[$__rate_interval])",
     "legendFormat": "success::{{loop}}"
    },
    {
     "expr": "irate(logical_commit_failure_total[$__rate_interval])",
     "legendFormat": "failure::{{loop}}"
    }
   ]
  },
  {
   "title": "Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(logical_commit_latency_seconds[$__rate_interval])",
     "legendFormat": "{{loop}}"
    }
   ]
  },
  {
   "title": "CDC http payload size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by(le) (irate(http_payload_in_bytes_total_bucket{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CDC http payload rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(http_payload_in_bytes_total_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CDC http latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "sum by (le) (irate(http_latency_seconds_bucket{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mutation application latency",
   "type": "heatmap",
   "description": "How long it's taking to apply individual mutations to the target.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sum by(le) (irate(apply_duration_seconds_bucket{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Mutation staging latency",
   "type": "heatmap",
   "description": "How long it takes for incoming mutations to be stored within the staging tables.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum by(le) (irate(stage_store_duration_seconds_bucket{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CDC pool dial latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "sum by(le) (irate(pool_dial_latency_seconds_bucket{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CDC SQL pool ready latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum by(le) (irate(pool_sql_ready_latency_seconds_bucket{}[$__rate_interval]))"
    }
   ]
  }
 ]
}