# Copyright 2023 The Cockroach Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Ensure that all go modules are cached within the local GitHub cache
# before executing the full test matrix. We've been seeing some requests
# to the upstream module cache fail due to network rate-limiting.
name: Warm Golang Build Cache
permissions:
  contents: read
on:
  workflow_call:
  workflow_dispatch:
jobs:
  # This is the usual case, where we just want to see if the cache exists.
  check:
    name: Check if cache exists
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.setup.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        id: setup
        uses: actions/setup-go@v5
        with:
          # This step is going to create a mostly-empty cache; there's
          # no argument to use-but-don't-push the cache. We'll tweak the
          # dependency-path to include another file, so that this step
          # uses a sentinel cache key that's separate from the default.
          cache-dependency-path: |
            go.sum
            ./.github/workflows/go-build-cache.yaml
          go-version-file: 'go.mod'

  # Start a job on a larger machine only when we need to build.
  build:
    name: Regenerate build cache
    # Managed by dev-inf team.
    runs-on: ubuntu-latest-8-core
    needs: check
    # Outputs are strings, not booleans.
    if: ${{ needs.check.outputs.cache-hit != 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        id: setup
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Download modules
        run: go mod download

      - name: Prebuild
        # Keep options in sync with golang.yaml
        # The extra . is to build the Replicator binary itself.
        run: |
          go build . ./...
          CGO_ENABLED=0 go build . ./...
